/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type { Likes, LikesInterface } from "../Likes";

const _abi = [
  {
    inputs: [
      {
        name: "_addressBook",
        type: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        name: "itemId",
        type: "uint256",
      },
      {
        name: "account",
        type: "address",
      },
    ],
    name: "like",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        name: "_type",
        type: "string",
      },
    ],
    name: "isValidContract",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        name: "arg0",
        type: "uint256",
      },
    ],
    name: "itemLikesCount",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        name: "arg0",
        type: "uint256",
      },
      {
        name: "arg1",
        type: "address",
      },
    ],
    name: "itemLikesAccounts",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x602061036d6000396000518060a01c610368576040526040516300000330526103306100376300000000396103306020016300000000f3600436101561000d57610325565b60003560e01c3461032b5763b20be2f68118610248576024358060a01c61032b5760405263ccf1454a60a05260208060c05260066060527f4d696e746572000000000000000000000000000000000000000000000000000060805260608160c0018151808252602083016020830181518152505050805180602083010181600003601f163682375050601f19601f825160200101169050905081015050602060a0606460bc60206103306000396000515afa6100ce573d600060003e3d6000fd5b60203d1061032b5760a0518060a01c61032b576101205261012051331861032b5763ccf1454a60c05260208060e05260046080527f4974656d0000000000000000000000000000000000000000000000000000000060a05260808160e0018151808252602083016020830181518152505050805180602083010181600003601f163682375050601f19601f825160200101169050905081015050602060c0606460dc60206103306000396000515afa61018c573d600060003e3d6000fd5b60203d1061032b5760c0518060a01c61032b576101405261014051606052600435634f6ccce760805260043560a052602060806024609c6060515afa6101d7573d600060003e3d6000fd5b60203d1061032b576080511861032b576000600435602052600052604060002080546001818183011061032b578082019050905081555060016004356020526000526040600020806040516020526000526040600020905080546001818183011061032b5780820190509050815550005b63a7a66fa681186102ba57600435600401600c81351161032b57803580604052602082018035606052505050600560c0527f4c696b657300000000000000000000000000000000000000000000000000000060e05260c080516020820120905060405160602014610100526020610100f35b63eb2e092681186102df57600060043560205260005260406000205460405260206040f35b637196548a8118610323576024358060a01c61032b576040526001600435602052600052604060002080604051602052600052604060002090505460605260206060f35b505b60006000fd5b600080fd005b600080fd";

type LikesConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LikesConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Likes__factory extends ContractFactory {
  constructor(...args: LikesConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    _addressBook: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Likes> {
    return super.deploy(_addressBook, overrides || {}) as Promise<Likes>;
  }
  override getDeployTransaction(
    _addressBook: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_addressBook, overrides || {});
  }
  override attach(address: string): Likes {
    return super.attach(address) as Likes;
  }
  override connect(signer: Signer): Likes__factory {
    return super.connect(signer) as Likes__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LikesInterface {
    return new utils.Interface(_abi) as LikesInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Likes {
    return new Contract(address, _abi, signerOrProvider) as Likes;
  }
}
